apiVersion: apps/v1
kind: Deployment
metadata:
  name: refresh-owid-data
  namespace: covid
spec:
  selector:
    matchLabels:
      run: refresh-owid-data
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        run: refresh-owid-data
    spec:
      containers:
      - name: refresh-owid-data
        image: xgis/covid-refresh-owid-data
        env:
        - name: COVID_DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: host
        - name: COVID_DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: name
        - name: COVID_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: COVID_DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: pass
        ports:
        - containerPort: 80
